[package]
name = "controlpass_modular_fixed"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe      = "0.27"
egui        = "0.27"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
tokio       = { version = "1", features = ["full"] }
odbc-api    = "0.26"
